export const GET_LISTS_START = "GET_LISTS_START";
export const GET_LISTS_SUCCESS = "GET_LISTS_SUCCESS";
export const GET_LISTS_FAILURE = "GET_LISTS_FAILURE";
export const GET_POST_DETAIL = "GET_POST_DETAIL";
